config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :bookmarks
  root 'bookmarks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  include AlgoliaSearch
  before_create :update_thumbnail

  belongs_to :user

  algoliasearch do
    attribute :title, :url, :created_at, :description, :favicon, :image, :viewable_by

    attributesForFaceting [
    'filterOnly(viewable_by)'
  ]
  end

  def update_thumbnail
  	link = LinkThumbnailer.generate(self.url)
  	self.title = link.title
  	self.description = link.description
  	self.favicon = link.favicon
  	self.image = link.images.first.src.to_s
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookmarks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation])
	end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /bookmarks
  # GET /bookmarks.json
  def index

  @secured_api_key = Algolia.generate_secured_api_key(
  '2887c3d50be0928409ed49d93cfbc6a7',
   { filters: 'viewable_by:' + current_user.id.to_s }
)
    @bookmarks = Bookmark.all
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = current_user.bookmarks.new(bookmark_params)


    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to bookmarks_path, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to bookmarks_path, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url, :description, :favicon, :image, :user_id, :viewable_by)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

   def after_update_path_for(resource)
      edit_user_registration_path
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  	@q = params['q']
    return if @q.blank?
    @hits = Bookmark.algolia_search(@q)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/bookmarks/_form.html.erb
<div class="new-bookmark mb-2 col-md-7">
 <%= form_with(model: @bookmark, local: true) do |form| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>
      <ul>
      <% @bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field new-bookmark-input">
    <%= form.text_field :url, placeholder: "Add a new URL" %>
  </div>

  <div class="field new-bookmark-input">
    <%= form.hidden_field :viewable_by, value: current_user.id %>
  </div>

  <div class="actions hidden">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<div class="container">

 <div id="search-box" class="col-md-7">
</div>


<div id="refinement-list">
</div>

<div id="hits">
</div>

</div>

<script>
  $('#myModal').on('shown.bs.modal', function () {
  $('#myInput').trigger('focus')
})
</script>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-body new-bookmark">
        <%= form_with(model: @bookmark, local: true) do |form| %>
          <% if @bookmark.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>
              <ul>
              <% @bookmark.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field new-bookmark-input">
            <%= form.text_field :url, placeholder: "Add a new URL", autocomplete: :off %>
          </div>

          <div class="field new-bookmark-input">
            <%= form.hidden_field :viewable_by, value: current_user.id %>
          </div>

          <div class="actions hidden">
            <%= form.submit %>
          </div>
        <% end %>
      </div>
      
    </div>
  </div>
</div>




<script>
  const search = instantsearch({
  appId: 'JH5PBQKH6H',
  apiKey: '<%= @secured_api_key %>',
  indexName: 'Bookmark',
  routing: true,
  searchParameters: {
    attributesToSnippet: [
  'description:31;'
    ]
  }
  
});

  // initialize SearchBox
  search.addWidget(
    instantsearch.widgets.searchBox({
      container: '#search-box',
      focus: false,
      placeholder: 'Search bookmarks, tags, etc...'
    })
  );


  search.addWidget(
    instantsearch.widgets.hits({
      container: '#hits',
      templates: {
        empty: 'No results',
        item: '<div class="bookmark-container col-md-7"><a href="{{{url}}}"> {{{_highlightResult.title.value}}} {{{_highlightResult.url.value}}}</a><div class="bookmark-description">{{{_snippetResult.description.value}}}</div></div><div>'
      }
    })
  );

search.start();
</script>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="container col-md-5 alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar mb-4 container">
  <div class="col-md-12 branding text-center">
  <%= link_to "Bookmarks", bookmarks_path, class: "navbar-brand" %>
  <%= link_to "My Settings", edit_user_registration_path, class: "nav-link" %>
  <%= link_to "Add Link", "#", data: { target: "#exampleModal", toggle: "modal" }, class: "nav-link" %>

 </div>
</nav>

app/views/layouts/_search-box.html.erb
<div class="search-box">
    <%= form_tag("/search", method: "get") do %>
      <%= text_field_tag :q, nil, placeholder:'Search the site' %>
      <%= submit_tag("Search") %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoRecording</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/instantsearch.js@2.9.0/dist/instantsearch.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@2.9.0"></script>

  </head>

  <body>

  <%= render 'layouts/navbar' %>
  
  <div class="main">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
    
  </body>
</html>

app/views/pages/home.html.erb
Test

app/views/search/index.html.erb
<div class="search-results">
    <h1>Search results</h1>
    <p>
        <span class="faded">There are <%= @hits.count %> results for "<%= @q %>"</span>
    </p>
    <% if @hits %>
      <div class="hits">
          <% @hits.each do |hit| %>
            <div class="hit">
              <div class="hit-date">
                  <%= raw(hit["created_at"].strftime('%b %d,<br/> %Y')) %>
              </div>
              <div class="hit-link">
                  <%= link_to hit['title'], bookmark_path(hit) %>
              </div>
            </div>
          <% end %>
      </div>
    <% end %>
</div>